/*
 * Winston Zhang (wyz5rge)
 * CS 2110, Professor Graham
 * Homework 2
 * BackgroundImage.java
 * September 25, 2020
 */

public class BackgroundImage {

	//Instance variables
	private String imageFileName;
	private String title;
	private String description;
	
	//Constructor
	public BackgroundImage(String i, String t, String d)
	{
		this.imageFileName = i;
		this.title = t;
		this.description = d;
	}
	public BackgroundImage()
	{
		this.imageFileName = "";
		this.title = "";
		this.description = "";
	}
	
	//Getter methods for instance variables
	public String getImageFileName() 
	{
		return imageFileName;
	}
	
	public String getTitle() 
	{
		return title;
	}
	
	public String getDescription()
	{
		return description;
	}
	
	//Setter methods for instance variables
	public void setImageFileName(String imageFileName) 
	{
		this.imageFileName = imageFileName;
	}
	
	public void setTitle(String title) 
	{
		this.title = title;
	}
	
	public void setDescription(String description) 
	{
		this.description = description;
	}
	
	/*
	 * toString method, returns title <description>
	 * e.g. Italian people <Image of Benito Mussolini>
	 */
	@Override
	public String toString()
	{
		return title + " <" + description + ">";
	}
	
	/*
	 * equals method generated by Eclipse
	 * returns true if title, description, and imageFileName are the same
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BackgroundImage other = (BackgroundImage) obj;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (imageFileName == null) {
			if (other.imageFileName != null)
				return false;
		} else if (!imageFileName.equals(other.imageFileName))
			return false;
		if (title == null) {
			if (other.title != null)
				return false;
		} else if (!title.equals(other.title))
			return false;
		return true;
	}
	
	
}
