/*
 * Winston Zhang (wyz5rge)
 * CS 2110, Professor Graham
 * Homework 2
 * Rating.java
 * Setpember 25, 2020
 */


public class Rating {

	//Instance variables
	private int score;
	private User user;
	
	//Constructor
	public Rating(User u, int s)
	{
		this.user = u;
		this.score = s;
	}
	
	public Rating()
	{
		this.user = new User();
		this.score = 0;
	}
	
	//Getter methods for instance variables
	public int getScore() {
		return score;
	}
	public User getUser() {
		return user;
	}

	//Setter methods for instance variables
	public void setScore(int score) {
		if(score > 0)
			this.score = 1;
		else if(score < 0)
			this.score = -1;
		else if(score == 0)
			this.score = 0;
	}
	public void setUser(User user) {
		this.user = user;
	}
	
	public void setRating(int rate)
	{
		if(rate > 0)
			this.setScore(1);
		else if(rate < 0)
			this.setScore(-1);	
		else if(score == 0)
			this.setScore(0);
	}
	
	/*
	 * toString method, returns "username rates score"
	 * e.g. Benito Mussolini rates 1
	 */
	@Override
	public String toString()
	{
		return user.getUserName() + " rates " + score;
	}

	//equals methods generated by Eclipse, returns true if user and score are equal
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Rating other = (Rating) obj;
		if (score != other.score)
			return false;
		if (user == null) {
			if (other.user != null)
				return false;
		} else if (!user.equals(other.user))
			return false;
		return true;
	}
}
